import type { RBACGraph } from '../types/rbac'
import { serializeGraphData } from './serialize'

export function exportExpressMiddleware(graph: RBACGraph): string {
  return `/**
 * Auto-generated by Permissable. Do not hand-edit the DATA block below —
 * regenerate it from the visual builder instead. Wiring code beneath it
 * is yours to customize.
 */

${serializeGraphData(graph)}

function resolveRoleClosure(roleId) {
  const seen = new Set();
  const stack = [roleId];
  while (stack.length) {
    const id = stack.pop();
    if (seen.has(id)) continue;
    seen.add(id);
    const node = NODES[id];
    (node && node.extends ? node.extends : []).forEach((p) => stack.push(p));
  }
  return [...seen];
}

function resolveResourceAncestors(resourceId) {
  const chain = [];
  let current = resourceId;
  const seen = new Set();
  while (current && !seen.has(current)) {
    seen.add(current);
    chain.push(current);
    const node = NODES[current];
    current = node ? node.parentId : null;
  }
  return chain;
}

/**
 * Core check, usable outside of Express too (jobs, GraphQL resolvers, etc).
 * @param {string[]} userRoleIds - role ids assigned to the user
 * @param {string} permissionId
 * @param {string} resourceId
 */
function can(userRoleIds, permissionId, resourceId) {
  const expandedRoles = new Set();
  for (const r of userRoleIds) resolveRoleClosure(r).forEach((x) => expandedRoles.add(x));
  const ancestorChain = resolveResourceAncestors(resourceId);

  return GRANTS.some((g) => {
    if (!expandedRoles.has(g.roleId)) return false;
    if (g.permissionId !== permissionId) return false;
    if (g.resourceId === resourceId) return true;
    const idx = ancestorChain.indexOf(g.resourceId);
    return idx > 0 && g.cascade;
  });
}

/**
 * Express middleware factory.
 *
 * Usage:
 *   app.delete('/projects/:id', requirePermission('delete', 'res_project'), handler)
 *
 * getUserRoleIds and getResourceId are hooks you provide, since only your
 * app knows how to pull the user's roles (e.g. req.user.roleIds) and which
 * resource node a given route maps to (often a static id, sometimes derived
 * from req.params).
 */
function requirePermission(permissionId, resourceId, options = {}) {
  const getUserRoleIds = options.getUserRoleIds || ((req) => (req.user && req.user.roleIds) || []);
  const getResourceId = options.getResourceId || (() => resourceId);

  return function (req, res, next) {
    const roleIds = getUserRoleIds(req);
    const resolvedResourceId = getResourceId(req);
    if (can(roleIds, permissionId, resolvedResourceId)) {
      return next();
    }
    return res.status(403).json({ error: 'Forbidden', permission: permissionId, resource: resolvedResourceId });
  };
}

module.exports = { can, requirePermission, NODES, GRANTS };
`
}
