import type { RBACGraph } from '../types/rbac'
import { serializeGraphData } from './serialize'

export function exportNextjsMiddleware(graph: RBACGraph): string {
  return `/**
 * Auto-generated by Permissable. Do not hand-edit the DATA block below —
 * regenerate it from the visual builder instead. Wiring code beneath it
 * is yours to customize.
 *
 * Usage in an App Router route handler:
 *
 *   import { can } from '@/lib/rbac';
 *
 *   export async function DELETE(req: Request, { params }: { params: { id: string } }) {
 *     const roleIds = await getRoleIdsForRequest(req);
 *     if (!can(roleIds, 'perm_delete', 'res_project')) {
 *       return new Response('Forbidden', { status: 403 });
 *     }
 *     // ... handler
 *   }
 *
 * Or as reusable middleware wrapping a handler:
 *
 *   export const DELETE = withPermission('perm_delete', 'res_project')(handler);
 */

${serializeGraphData(graph)}

function resolveRoleClosure(roleId${''}: string): string[] {
  const seen = new Set<string>();
  const stack: string[] = [roleId];
  while (stack.length) {
    const id = stack.pop()!;
    if (seen.has(id)) continue;
    seen.add(id);
    const node = (NODES as any)[id];
    ((node && node.extends) || []).forEach((p: string) => stack.push(p));
  }
  return [...seen];
}

function resolveResourceAncestors(resourceId: string): string[] {
  const chain: string[] = [];
  let current: string | null | undefined = resourceId;
  const seen = new Set<string>();
  while (current && !seen.has(current)) {
    seen.add(current);
    chain.push(current);
    const node = (NODES as any)[current];
    current = node ? node.parentId : null;
  }
  return chain;
}

export function can(userRoleIds: string[], permissionId: string, resourceId: string): boolean {
  const expandedRoles = new Set<string>();
  for (const r of userRoleIds) resolveRoleClosure(r).forEach((x) => expandedRoles.add(x));
  const ancestorChain = resolveResourceAncestors(resourceId);

  return (GRANTS as any[]).some((g) => {
    if (!expandedRoles.has(g.roleId)) return false;
    if (g.permissionId !== permissionId) return false;
    if (g.resourceId === resourceId) return true;
    const idx = ancestorChain.indexOf(g.resourceId);
    return idx > 0 && g.cascade;
  });
}

type RouteHandler = (req: Request, ctx: any) => Promise<Response> | Response;

/**
 * Wraps a route handler with a permission check. You must supply how to
 * derive the user's role ids from the request (e.g. decode a session/JWT).
 */
export function withPermission(
  permissionId: string,
  resourceId: string,
  getUserRoleIds: (req: Request) => Promise<string[]> | string[] = async () => [],
) {
  return (handler: RouteHandler): RouteHandler => {
    return async (req, ctx) => {
      const roleIds = await getUserRoleIds(req);
      if (!can(roleIds, permissionId, resourceId)) {
        return new Response(JSON.stringify({ error: 'Forbidden', permission: permissionId, resource: resourceId }), {
          status: 403,
          headers: { 'Content-Type': 'application/json' },
        });
      }
      return handler(req, ctx);
    };
  };
}

export { NODES, GRANTS };
`
}
